import type { Vet } from "@/modules/vets/types/vet.type";

export interface ConditionAppointments {
  appointmentDetailId: number | null;
  appointmentId: number | null;
  appointmentDetailCode: string;
  vetId: number | null;
  serviceType: number;
  healthConditionId: number | null;
  appointmentDate: string;
  appointmentStatus: number;
  notes: string;
  createdAt: string;
  createdBy: string;
  modifiedAt: string;
  modifiedBy: string;
  vet: Vet;
  healthCondition: {
    healthConditionId: number | null;
    petId: number | null;
    vetId: number | null;
    microchipItemId: number | null;
    conditionCode: string;
    heartRate: string;
    breathingRate: string;
    weight: string;
    temperature: string;
    ehnm: string;
    skinAFur: string;
    digestion: string;
    respiratory: string;
    excrete: string;
    behavior: string;
    psycho: string;
    different: string;
    conclusion: string;
    price: number;
    checkDate: string;
    status: string;
    createdAt: string;
    createdBy: string;
    modifiedAt: string;
    modifiedBy: string;
    isDeleted: boolean;
  };
  appointment: {
    appointmentId: number | null;
    customerId: number | null;
    petId: number | null;
    appointmentCode: string;
    appointmentDate: string;
    serviceType: number;
    location: number;
    address: string;
    appointmentStatus: number;
    createdAt: string;
    createdBy: string;
    modifiedAt: string;
    modifiedBy: string;
    isDeleted: boolean;
    customerResponseDTO: {
      customerId: number | null;
      accountId: number | null;
      membershipId: number | null;
      customerCode: string;
      fullName: string;
      userName: string;
      image: string;
      phoneNumber: string;
      dateOfBirth: string;
      gender: string;
      address: string;
      currentPoints: number;
      createdAt: string;
      createdBy: string;
      modifiedAt: string;
      modifiedBy: string;
      isDeleted: boolean;
      accountResponseDTO: {
        accountId: number | null;
        email: string;
        role: number;
      };
    };
    petResponseDTO: {
      petId: number | null;
      customerId: number | null;
      petCode: string;
      name: string;
      species: string;
      breed: string;
      gender: string;
      dateOfBirth: string;
      placeToLive: string;
      placeOfBirth: string;
      image: string;
      weight: string;
      color: string;
      nationality: string;
      isSterilized: boolean;
      isDeleted: boolean;
    };
  };
  payment: {
    paymentId: number | null;
    appointmentDetailId: number | null;
    customerId: number | null;
    vaccineBatchId: number | null;
    microchipId: number | null;
    vaccinationCertificateId: number | null;
    healthConditionId: number | null;
    paymentCode: string;
    amount: number;
    paymentDate: string;
    paymentMethod: string;
    paymentStatus: 1 | 2 | 3;
    checkoutUrl: string;
    qrCode: string;
    createdAt: string;
    createdBy: string;
    modifiedAt: string;
    modifiedBy: string;
    isDeleted: boolean;
    url: string;
  };
}
