import type { ConditionAppointments } from "@/modules/condition-appointment";
import type { Customer } from "@/modules/customers";
import type { MicrochipItem } from "@/modules/microchip-item";
import type { Microchip } from "@/modules/microchips";
import type { VaccinationApp } from "@/modules/vaccination-appointment";
import type { VaccineBatch } from "@/modules/vaccine-batch";
import type { Vet } from "@/modules/vets/types/vet.type";

export interface Payment {
  paymentId: number | null;
  appointmentDetailId: number | null;
  customerId: number | null;
  vaccineBatchId: number | null;
  microchipId: number | null;
  vaccinationCertificateId: number | null;
  healthConditionId: number | null;
  paymentCode: string;
  voucherCode: string;
  amount: number;
  paymentDate: string;
  paymentMethod: string;
  paymentStatus: number;
  checkoutUrl: string;
  qrCode: string;
  createdAt: string;
  createdBy: string;
  modifiedAt: string;
  modifiedBy: string;
  isDeleted: boolean;
  url: string;
  isRetrieved: boolean;
  appointmentDetail: {
    appointmentDetailId: number | null;
    appointmentId: number | null;
    vetId: number | null;
    serviceType: number;
    microchipItemId: number | null;
    passportId: number | null;
    healthConditionId: number | null;
    vaccineBatchId: number | null;
    diseaseId: number | null;
    appointmentDetailCode: string;
    dose: string;
    reaction: string;
    nextVaccinationInfo: string;
    appointmentDate: string;
    appointmentStatus: number;
    temperature: string;
    heartRate: string;
    generalCondition: string;
    others: string;
    notes: string;
    createdAt: string;
    createdBy: string;
    modifiedAt: string;
    modifiedBy: string;
    isDeleted: boolean;
    vet: Vet;
    microchipItem: MicrochipItem;
    petPassport: null;
    healthCondition: ConditionAppointments["healthCondition"];
    vaccineBatch: VaccineBatch;
    disease: VaccinationApp["appointmentHasDiseaseResponseDTO"]["disease"];
  };
  customer: Customer;
  vaccineBatch: VaccineBatch;
  microchip: Microchip;
  healthCondition: ConditionAppointments["healthCondition"];
}
